name: bi-weekly-actions
run-name: bi-weekly-actions
on:
  schedule:
    - cron: '0 4 * * 1'
  workflow_dispatch:
env:
  FIRST_RUN_DATE: 2023-12-17
jobs:
  set_weekdiff:
    runs-on: ubuntu-latest
    outputs:
      weekdiff: ${{ steps.weekdiff.outputs.weekdiff }}
    steps:
      - name: Calculate weekdiff
        id: weekdiff
        run: |
          current_date=$(date +%Y-%m-%d)
          start=$(date -d ${{ env.FIRST_RUN_DATE }} +%s)
          end=$(date -d $current_date +%s)
          weekdiff=$((((end-start) / 60 / 60 / 24 / 7) % 2))
          echo "weekdiff=$weekdiff" >> "$GITHUB_OUTPUT"
  action:
    if: ${{ needs.set_weekdiff.outputs.weekdiff != 0 }}  
    runs-on: ubuntu-latest
    needs:
      - set_weekdiff
    steps:
    - run: echo "The bi-weekly action is running!"
