name: bi-weekly-actions
run-name: bi-weekly-actions
on:
  #schedule:
  #  - cron: '0 4 * * 1'
  workflow_dispatch:
env:
  FIRST_RUN_DATE: 2023-12-17
jobs:
  set_weekdiff:
    runs-on: ubuntu-latest
    outputs:
      weekdiff: ${{ steps.weekdiff.outputs.weekdiff }}
    steps:
      - name: Calculate weekdiff
        id: weekdiff
        run: |
          iterator_bandwidth=$(node -e "console.log(JSON.stringify([...Array(${{ github.event.inputs.bandwidth_times }}).keys()]))")
          echo $iterator_bandwidth
          echo "iterator_bandwidth=$iterator_bandwidth" >> "$GITHUB_OUTPUT"
  storage:
    if: ${{ needs.set_variables.outputs.iterator_storage != '[]' && needs.set_variables.outputs.iterator_storage != '' }}  
    runs-on: ubuntu-latest
    needs:
      - set_weekdiff   
    strategy:
      max-parallel: 1 
      matrix:
        i: ${{ fromJSON(needs.set_variables.outputs.iterator_storage) }}
    steps:
    - uses: actions/checkout@v3
    - run: |
       GIT_LFS_SKIP_SMUDGE=1 git pull        
        rnd=$((10 + $RANDOM % 300))
        size=$(expr ${{ github.event.inputs.storage }}000 + $rnd)
        echo "Generating $size Mb"
        fallocate -l ${size}Mb ${size}Mb_$(date +%s).psd        
        git config user.name pac-man
        git config user.email pac-man@github.com
        git lfs track "*.psd"
        git add .
        git commit -m "Added large file"
        result=$(git push 2>&1) || true
        echo $result
        if [[ "$result" == *"Write access to repository not granted"* ]]; then
          echo "::error ::Pac-Man is not authorized to push into the repository. Open Enterprise > Policies > Actions. Navigate to \"Workflow permissions\". Set to \"Read and write permissions\". Run Pac-Man again."
          exit 128
        fi