name: bi-weekly-actions
run-name: bi-weekly-actions
on:
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:
env:
  # The cron has to be set to run on the same weekday as this date. 12/17 is Sunday, so the cron is set to run on Sunday.
  FIRST_RUN_DATE: 2023-12-17
jobs:
  set_weekdiff:
    runs-on: ubuntu-latest
    outputs:
      weekdiff: ${{ steps.weekdiff.outputs.weekdiff }}
    steps:
      - name: Calculate weekdiff
        id: weekdiff
        run: |
          current_date=$(date +%Y-%m-%d)
          start=$(date -d ${{ env.FIRST_RUN_DATE }} +%s)
          end=$(date -d $current_date +%s)
          weekdiff=$((((end-start) / 60 / 60 / 24 / 7) % 2))
          echo "weekdiff=$weekdiff" >> "$GITHUB_OUTPUT"
          echo "FIRST_RUN_DATE: ${{ env.FIRST_RUN_DATE }}" >> $GITHUB_STEP_SUMMARY
          echo "current_date: $current_date" >> $GITHUB_STEP_SUMMARY
          echo "weekdiff: $weekdiff" >> $GITHUB_STEP_SUMMARY
          if [ $weekdiff -eq 0 ]; then
            echo "🟢 It's the first week of the bi-weekly cycle. The action is going to run." >> $GITHUB_STEP_SUMMARY
          else
            echo "🔴 It's the second week of the bi-weekly cycle. The action is going to be skipped." >> $GITHUB_STEP_SUMMARY
          fi
  action:
    if: ${{ needs.set_weekdiff.outputs.weekdiff == 0 }}  
    runs-on: ubuntu-latest
    needs:
      - set_weekdiff
    steps:
    - run: echo "The bi-weekly action is running!"
